---
- name: Packages
  apt:
      pkg:
          - coturn

- name: Addresses
  addrs:
      hostname: "{{ pbx_hostname }}"
  register: coturn_addrs

- name: Set facts
  set_fact:
      coturn_ipv4_addr: "{{ coturn_addrs.ipv4_addr }}"
      coturn_ipv6_addr: "{{ coturn_addrs.ipv6_addr }}"

- name: Configuration
  notify:
      - restart coturn service
  template:
      src: turnserver.conf
      dest: /etc/turnserver.conf


# Handlers.

- name: Handlers
  meta: flush_handlers
