---
- name: Restart service
  listen:
      - restart pbx-web service
  systemd:
      name: pbx-web.service
      state: restarted

- name: Restart nginx service
  listen:
      - restart nginx for pbx
  systemd:
      name: nginx.service
      state: restarted
