#!/bin/bash
# Write Let's Encrypt files to FreeSWITCH-friendly tls/wss files
# and email host admin unless the first arg is "silent".

# Generate new temp file.
HOSTNAME={{ hostname }}
CERT_DIR=/etc/letsencrypt/live/$HOSTNAME
FS_DIR=/opt/pbx/freeswitch
TMP=$FS_DIR/certs/tmp.pem
cat $CERT_DIR/fullchain.pem $CERT_DIR/privkey.pem > $TMP

# Write tls.pem.
OUT=$FS_DIR/certs/tls.pem
TLS_DIFF=$(diff -q $TMP $OUT 2>&1)
if [ -n "$TLS_DIFF" ]; then
    cp $TMP $OUT
    chmod 0600 $OUT
    chown pbx-fs.pbx-fs $OUT
fi

# Write wss.pem.
OUT=$FS_DIR/certs/wss.pem
WSS_DIFF=$(diff -q $TMP $OUT 2>&1)
if [ -n "$WSS_DIFF" ]; then
    cp $TMP $OUT
    chmod 0600 $OUT
    chown pbx-fs.pbx-fs $OUT
fi

# Alert admin if either changes.
RUN_DIR=$FS_DIR/run
if [ -n "$TLS_DIFF" ] || [ -n "$WSS_DIFF" ]; then
    touch $RUN_DIR/restart
    if [ "$1" != 'silent' ]; then
        ADDR="{{ admin_email }}"
        BODY="Let's Encrypt cert renewed. Restart FreeSWITCH by hand."
        SUBJECT="[$HOSTNAME] FreeSWITCH cert update"
        echo "$BODY" | mail -s "$SUBJECT" "$ADDR"
    fi
fi

# Cleanup.
rm $TMP
#/usr/bin/env | /usr/bin/fold -w80 > /tmp/post-mail.txt
