---

# OS.

- name: Packages
  apt:
      pkg:
          - git
          - python3-venv
          - python3-dev
          - build-essential

- name: User
  user:
      name: pbx-web
      shell: /usr/sbin/nologin


# Django project.

- name: Deployment directory
  file:
      path: /opt/pbx
      state: directory

- name: Directory
  file:
      path: /opt/pbx/web
      state: directory
      owner: pbx-web
      group: pbx-web
      mode: 0700

- name: Repo
  notify:
      - restart pbx-web service
  become: true
  become_user: pbx-web
  git:
      repo: "{{ web_repo }}"
      dest: /opt/pbx/web
      version: "{{ web_version }}"
      force: true
      depth: 1
  register: web_clone
  # Clean
  # Upgrade
  # Requirements
  # Migrate

- name: Clean
  file:
      path: /opt/pbx/static
      state: absent
  when: web_clone is changed

- name: Stat static
  stat:
      path: /opt/pbx/static
  register: web_static
  # Static.

- name: Static
  copy:
      src: /opt/pbx/web/static
      dest: /opt/pbx
      remote_src: true
      owner: nginx
      group: nginx
      mode: 0700
  when: not web_static.stat.exists

- name: Settings
  notify:
      - restart pbx-web service
  become: true
  become_user: pbx-web
  template:
      src: settings.py
      dest: /opt/pbx/web/var/settings.py


# Venv

- name: Venv
  notify:
      - restart pbx-web service
  become: true
  become_user: pbx-web
  command: python3 -m venv venv
  args:
      chdir: /opt/pbx/web/var
      creates: /opt/pbx/web/var/venv
  register: web_venv
  # Upgrade
  # Requirements

- name: Upgrade
  become: true
  become_user: pbx-web
  command: /opt/pbx/web/var/venv/bin/pip install --upgrade pip setuptools wheel pip-tools
  when: web_clone is changed or web_venv is changed

- name: Requirements
  become: true
  become_user: pbx-web
  command: /opt/pbx/web/var/venv/bin/pip-sync requirements.txt
  args:
      chdir: /opt/pbx/web
  when: web_clone is changed or web_venv is changed


# Systemd service.

- name: Service detection script
  copy:
      src: altp.bash
      dest: /opt/pbx/web/var/altp
      owner: pbx-web
      group: pbx-web
      mode: 0700

- name: Service file
  notify:
      - restart pbx-web service
  template:
      src: service
      dest: /etc/systemd/system/pbx-web.service
      mode: 0644

- name: Service state
  systemd:
      name: pbx-web.service
      enabled: true
      daemon-reload: true


# Nginx servers.

- name: Nginx servers
  notify:
      - restart nginx for pbx
  template:
      src: nginx.conf
      dest: /etc/nginx/conf.d/pbx.conf
      mode: 0644


# Database migration.

- name: Stat db
  stat:
      path: /opt/pbx/web/var/db.sqlite3
  register: web_db
  # Migrate

- name: Migrate
  become: true
  become_user: pbx-web
  command: /opt/pbx/web/var/venv/bin/python manage.py migrate
  args:
      chdir: /opt/pbx/web
  when: web_clone is changed or not web_db.stat.exists


# Handlers.

- name: Handlers
  meta: flush_handlers
