---

# OS.

- name: Packages
  apt:
      pkg:
          - libnginx-mod-nchan
          - git
          - python3-venv
          - python3-dev
          - build-essential

- name: User
  user:
      name: peers-web
      shell: /usr/sbin/nologin


# Django project.

- name: Deployment directory
  file:
      path: /opt/peers
      state: directory

- name: Directory
  file:
      path: /opt/peers/web
      state: directory
      owner: peers-web
      group: peers-web
      mode: 0700

- name: Repo
  notify:
      - restart peers web service
  become: true
  become_user: peers-web
  git:
      repo: "{{ web_repo }}"
      dest: /opt/peers/web
      version: "{{ web_version }}"
      force: true
      depth: 1
  register: web_clone
  # Clean
  # Upgrade
  # Requirements
  # Migrate

- name: Clean
  file:
      path: /opt/peers/static
      state: absent
  when: web_clone is changed

- name: Stat static
  stat:
      path: /opt/peers/static
  register: web_static
  # Static.

- name: Static
  copy:
      src: /opt/peers/web/static
      dest: /opt/peers
      remote_src: true
      owner: www-data
      group: www-data
      mode: 0700
  when: not web_static.stat.exists

- name: Settings
  notify:
      - restart peers web service
  become: true
  become_user: peers-web
  template:
      src: settings.py
      dest: /opt/peers/web/var/settings.py


# Venv

- name: Venv
  notify:
      - restart peers web service
  become: true
  become_user: peers-web
  command: python3 -m venv venv
  args:
      chdir: /opt/peers/web/var
      creates: /opt/peers/web/var/venv
  register: web_venv
  # Upgrade
  # Requirements

- name: Upgrade
  become: true
  become_user: peers-web
  command: /opt/peers/web/var/venv/bin/pip install --upgrade pip wheel pip-tools
  when: web_clone is changed or web_venv is changed

- name: Requirements
  become: true
  become_user: peers-web
  command: /opt/peers/web/var/venv/bin/pip-sync requirements.txt
  args:
      chdir: /opt/peers/web
  when: web_clone is changed or web_venv is changed


# Systemd tmpfiles.

- name: Run directory
  copy:
      src: tmpfile
      dest: /etc/tmpfiles.d/peers.conf
      mode: 0644

- name: Stat directory
  stat:
      path: /run/peers
  register: peers_tmpfile
  # Systemd-tmpfiles

- name: Systemd-tmpfiles
  command: /bin/systemd-tmpfiles --create peers.conf
  when: not peers_tmpfile.stat.exists


# Systemd service.

- name: Service file
  notify:
      - restart peers web service
  copy:
      src: service
      dest: /etc/systemd/system/peers-web.service
      mode: 0644

- name: Service state
  systemd:
      name: peers-web.service
      enabled: true
      daemon-reload: true


# Nginx servers.

- name: Nginx servers
  notify:
      - restart nginx service
  template:
      src: nginx.conf
      dest: /etc/nginx/conf.d/peers.conf
      mode: 0644


# Database migration.

- name: Stat db
  stat:
      path: /opt/peers/web/var/db.sqlite3
  register: web_db
  # Migrate

- name: Migrate
  become: true
  become_user: peers-web
  command: /opt/peers/web/var/venv/bin/python manage.py migrate
  args:
      chdir: /opt/peers/web
  when: web_clone is changed or not web_db.stat.exists


# Handlers.

- name: Handlers
  meta: flush_handlers
